import type { Metadata } from 'next';
import Link from 'next/link';
import '../styles/globals.css';
import LoginBtn from '../component/loginBtn';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/src/pages/api/auth/[...nextauth]';
import LogoutBtn from '../component/logoutBtn';
import NextAuthProvider from '../component/NextAuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <body>
        <NextAuthProvider>
          <div className='navbar'>
            <Link href='/' className='logo'>
              Forum
            </Link>
            <Link href={'/list'}>List</Link>
            {session ? (
              <>
                {session.user?.name} <LogoutBtn></LogoutBtn>
              </>
            ) : (
              <LoginBtn />
            )}
          </div>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
